export const FACEBOOK_SUCCESS = 'facebook_success'
export const FACEBOOK_FAIL = 'facebook_fail'
export const FETCH_JOBS = 'fetch_jobs'
export const LIKE_JOB = 'like_job'
export const CLEAR_JOBS = 'clear_jobs'
export const LOGOUT = 'logout'